#ifndef __MAVLINKPARAM_H__
#define __MAVLINKPARAM_H__

#include "mathTool.h"

enum
{
    /*System*/
    SYS_AUTOSTART,    
    SYS_AUTOCONFIG,
    SYS_PARAM_VER,
    SYS_SW_VER,
    /*MAVLink*/
    MAV_SYS_ID,
    MAV_COMP_ID,
    MAV_PROTO_VER,
    MAV_RADIO_ID,
    MAV_AIRFRAME_TYPE,
    MAV_USEHILGPS,
    MAV_FWDEXTSP,
    MAV_BROADCAST,
    /*Sensor Calibration*/
    CAL_BOARD_ID,
    CAL_GYRO0_ID,
    CAL_GYRO0_XOFF,
    CAL_GYRO0_YOFF,
    CAL_GYRO0_ZOFF,
    CAL_GYRO0_XSCALE,
    CAL_GYRO0_YSCALE,
    CAL_GYRO0_ZSCALE,
    CAL_MAG0_ID,
    CAL_MAG0_ROT,
    CAL_MAG0_XOFF,
    CAL_MAG0_YOFF,
    CAL_MAG0_ZOFF,
    CAL_MAG0_XSCALE,
    CAL_MAG0_YSCALE,
    CAL_MAG0_ZSCALE,
    CAL_ACC0_ID,
    CAL_ACC0_XOFF,
    CAL_ACC0_YOFF,
    CAL_ACC0_ZOFF,
    CAL_ACC0_XSCALE,
    CAL_ACC0_YSCALE,
    CAL_ACC0_ZSCALE,
    CAL_GYRO1_ID,
    CAL_GYRO1_XOFF,
    CAL_GYRO1_YOFF,
    CAL_GYRO1_ZOFF,
    CAL_GYRO1_XSCALE,
    CAL_GYRO1_YSCALE,
    CAL_GYRO1_ZSCALE,
    CAL_MAG1_ID,
    CAL_MAG1_ROT,
    CAL_MAG1_XOFF,
    CAL_MAG1_YOFF,
    CAL_MAG1_ZOFF,
    CAL_MAG1_XSCALE,
    CAL_MAG1_YSCALE,
    CAL_MAG1_ZSCALE,
    CAL_ACC1_ID,
    CAL_ACC1_XOFF,
    CAL_ACC1_YOFF,
    CAL_ACC1_ZOFF,
    CAL_ACC1_XSCALE,
    CAL_ACC1_YSCALE,
    CAL_ACC1_ZSCALE,    
    CAL_GYRO2_ID,
    CAL_GYRO2_XOFF,
    CAL_GYRO2_YOFF,
    CAL_GYRO2_ZOFF,
    CAL_GYRO2_XSCALE,
    CAL_GYRO2_YSCALE,
    CAL_GYRO2_ZSCALE,
    CAL_MAG2_ID,
    CAL_MAG2_ROT,
    CAL_MAG2_XOFF,
    CAL_MAG2_YOFF,
    CAL_MAG2_ZOFF,
    CAL_MAG2_XSCALE,
    CAL_MAG2_YSCALE,
    CAL_MAG2_ZSCALE,
    CAL_ACC2_ID,
    CAL_ACC2_XOFF,
    CAL_ACC2_YOFF,
    CAL_ACC2_ZOFF,
    CAL_ACC2_XSCALE,
    CAL_ACC2_YSCALE,
    CAL_ACC2_ZSCALE,    
    CAL_ACC_PRIME,
    CAL_GYRO_PRIME,
    CAL_MAG_PRIME,
    CAL_MAG_SIDES,
    CAL_BARO_PRIME,
    SENS_DPRES_OFF,
    SENS_DPRES_ANSC,
    SENS_BARO_QNH,
    SENS_BOARD_ROT,
    SENS_FLOW_ROT,
    SENS_BOARD_X_OFF,
    SENS_BOARD_Y_OFF,
    SENS_BOARD_Z_OFF,
    SENS_EXT_MAG_ROT,
    SENS_EXT_MAG,
    
    MAV_PARAM_NUM
};

bool MavParamSendCheck(void);
void MavParamSendEnable(int16_t num);
void MavParamSendEnableAll(void);
float MavParamGetValue(uint16_t num);
void MavParamSetValue(uint16_t num, float value);
int MavParamGetIdByName(char *name);
void MavParamSetDefault(void);
const char* MavParamGetString(uint8_t num);

#endif
